### ISSUE TITLE
exit function is not allowed in philosophers project. 

### ISSUE THREAD

**Issue by hamza-cskn** [suspectedoceano/dining_philosophers#1]
isn't that forbidden?
https://github.com/suspectedoceano/dining_philosophers/blob/7740eadc0140c371ce1cacca6c69dd802a7d9276/utils.c#L85

**Comment by suspectedoceano** [comment]
Yes it is, just ponder the overall algorithm. In real life code exit is not forbidden ✌️😁

**Comment by hamza-cskn** [comment]
Alright xd.
